### ISSUE TITLE
Write a function to aid downloading and placing data and code in the right folder

### ISSUE THREAD

**Issue by hansvancalster** [inbo/coding-club#14]
The `download data and code` section of the coding clubs (see slides) is always prone to errors and wasteful in time for participants that do not use  git. 

A way out of this would be to have a function that does this for the participant. That could be a function in the `inborutils` package for instance.

Ideally, a participant would open her/his RStudio coding club project and then in the console type:

`````
library(inborutils)
setup_codingclub_session(session = "YYYY-MM-DD")
``````

The function `setup_codingclub_session(session = "YYYY-MM-DD")` would then:

- download the needed data and code from this repo
- (unzip and) store the data and code in the correct folders

**Comment by niconoe** [comment]
I love the idea and would be willing to try implementing it (since I need real world R experience, I currently only practice during coding clubs).

However, I'm not sure when I could find time for this, especially now that I'm working less due to the corona crisis.

So feel free to do it if that's urgent or semi-urgent, otherwise I'd be happy to have a look!

**Comment by hansvancalster** [comment]
@niconoe That's fantastic!

I wasn't thinking about our next coding club, which is already next Thursday, but it would be great if we have a function by next months coding club. Would that be feasible?
We can certainly help you implementing the function.

**Comment by damianooldoni** [comment]
Thanks @niconoe.  I added you to assignees. Feel free to ask for any R help you would need.

**Comment by niconoe** [comment]
I'm revisiting this and I was wondering if we should restructure this repo, so there's, for each session, date subdirectories in `/data` and `/src` (for example, a data file for a session today would at `/data/01-04-2020/mydata.csv` instead of `/data/01042020_mydata.csv`?

That would make the implementation of this function a bit lighter, but I think it's also cleaner for users manually browsing the repository, hence the suggestion (it seems also more future-proof, as the umber of coding club sessions increases).  As a downside, I see it can break compatibility with existing slides.

Any opinion on that? If we reach a consensus, I can provide a pull request with the new structure.

**Comment by hansvancalster** [comment]
Yes, that makes sense to me (but stick to the YYYYMMDD format, you probably not intended to change this :wink: - I am also okay with YYYY-MM-DD).  

It will indeed break the links in the slides, but this can probably be also fixed automatically with regexp? Or even manually it would not be too much of a burden.

@damianooldoni what are your thoughts on this?

**Comment by damianooldoni** [comment]
Interesting idea. This would make the function very very simple indeed. But the function would be very easy in any case (e.g. using `starts_with("20200401")` function to select by filename). I find this ideda very good for the other reason: the directory `data` and `src` are getting extremely big and not so handy anymore. About back compatibility, I don't think it's a lot of work to change the links in slides. I can do it. 
Ah, I would use always yyyymmdd in directory name instead of dd-mm-yyyy. Using your example: `data/20200401` instead of `data/01-04-2020`.

**Comment by damianooldoni** [comment]
@hansvancalster: we answered at the same time and we gave same answer more or less :+1: So, @niconoe : I think we can proceed as you said.

**Comment by damianooldoni** [comment]
yes, directory name `data/2020-04-01` is more readable than `data/20200401`. But I would not change filenames, e.g. `20200401_mydata.csv`. @hansvancalster, @niconoe, what do you think?

**Comment by hansvancalster** [comment]
I think the date can be dropped from the filename. Why would you keep it?

**Comment by damianooldoni** [comment]
There were people using previous coding club material as exercises. They were downloading material and solving challenges of multiple coding club sessions at the same day. If you download them (manually) without date you don't know anymore so easily in which session they are used. My two cents: better a date (= unique identifier) more than less :smile: 

Moreover, if the function doesn't create a subdirectory called `2020-01-04` in `date` and `src` we need for sure date in filenames, otherwise the R scripts with challenges have same name and are put in same directory. But I suppose the function we are going to write create automatically such subdirectory if not already present?

**Comment by hansvancalster** [comment]
Fair points. Let's keep the date also in filenames.

**Comment by niconoe** [comment]
Thanks @damianooldoni and @hansvancalster!

I think it's best to be consistent in ate formats, so if we choose to keep the "20200104" format in file names, I think I'll use the same non-spaced format for the directory name (and `session` argument of `setup_codingclub_session()`. Any objection to that? I'll submit a PR soon with the new directory structure.

**Comment by hansvancalster** [comment]
This is implemented.
