### ISSUE TITLE
folder with solutions in root

### ISSUE THREAD

**Issue by PietrH** [inbo/coding-club#38]
In this commit: 6f621e2 you added a folder to the root of the repo, that I believe should probably be moved elsewhere

**Comment by damianooldoni** [comment]
In that commit I added a line to a file: [file_paths/file_path_df.csv](https://github.com/inbo/coding-club/commit/6f621e2e09e95d8518c6c47afaec75bee9cf9282#diff-ebf325982a7b42d9944f88865069b281eeb8cee7fa9860e2ae1bef2452be6433). The folder `file_paths` contains the paths of data and R scripts used in each session and it is there since years. It has been generated by @hansvancalster when he implemented the automatic download via `inborutils::setup_coding_club_session()`.

I don't really see a urgent reason to move the folder.

**Comment by PietrH** [comment]
I misunderstood! My mistake
